id: P009361
initial_creation_type: ocr
source_metadata:
  id: bdr:W3PD406
  title: ཀུན་བཟང་མཉམ་ཉིད་ཀྱི་རྒྱུད་སོགས་སྔགས་རྫོགས་ཀྱི་རྒྱུད་སྡེ།
  author: ''
  volumes:
    5409d7706a8a4708b49c6674b3ee19fd:
      image_group_id: I2PD18033
      title: ''
      volume_number: 1
      total_pages: 314
      base_file: v001.txt
