id: ICD7FCB9C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T03:52:00+00:00'
last_modified: '2022-06-08T10:28:11.423325+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD406
  title: ཀུན་བཟང་མཉམ་ཉིད་ཀྱི་རྒྱུད་སོགས་སྔགས་རྫོགས་ཀྱི་རྒྱུད་སྡེ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4889':
      image_group_id: I2PD18033
      title: ''
      total_pages: 314
      order: 1
      base_file: 4889.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
